setGeneric('getEnrichmentTable', function(object, ...) standardGeneric('getEnrichmentTable'))
setGeneric('plotRegionGeneAssociations', function(object, ...) standardGeneric('plotRegionGeneAssociations'))
setGeneric('availableCategories', function(object, ...) standardGeneric('availableCategories'))
setGeneric('plotRegionGeneAssociationGraphs', function(object, ...) standardGeneric('plotRegionGeneAssociationGraphs'))
setGeneric('getEnrichmentTables', function(object, ...) standardGeneric('getEnrichmentTables'))
setGeneric('getRegionGeneAssociations', function(object, ...) standardGeneric('getRegionGeneAssociations'))
setGeneric('shinyReport', function(object, ...) standardGeneric('shinyReport'))
setGeneric('availableOntologies', function(object, ...) standardGeneric('availableOntologies'))
