setGeneric('plotRegionGeneAssociationGraphs', function(job, ...) standardGeneric('plotRegionGeneAssociationGraphs'))
setGeneric('availableCategories', function(job, ...) standardGeneric('availableCategories'))
setGeneric('addRegionGeneAssociation', function(job, ...) standardGeneric('addRegionGeneAssociation'))
setGeneric('getEnrichmentTables', function(job, ...) standardGeneric('getEnrichmentTables'))
setGeneric('availableOntologies', function(job, ...) standardGeneric('availableOntologies'))
