# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

# == title
# Reduce by start and end
#
# == param
# -s Start positions. Sorted.
# -e End positions. Sorted.
#
# == details
# Only internally used.
#
# == value
# Total width of the reduced regions.
reduce_by_start_and_end <- function(s, e) {
    .Call('_rGREAT_reduce_by_start_and_end', PACKAGE = 'rGREAT', s, e)
}

