# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reduce_by_start_and_end <- function(s, e) {
    .Call('_rGREAT_reduce_by_start_and_end', PACKAGE = 'rGREAT', s, e)
}

