

# == title
# Shiny app on the GreatJob object
#
# == param
# -object The ``GreatJob`` object returned by `submitGreatJob`.
#
# == value
# A shiny app object.
#
# == example
# if(FALSE) {
# # pseudo code
# job = submitGreatJob(...)
# shinyReport(job)
# }
setMethod(f = "shinyReport",
	signature = "GreatJob",
	definition = function(object) {

	job = object

	all_ontologies = availableOntologies(job)
	message(qq("* download @{length(all_ontologies)} enrichment tables from GREAT server (tables will be cached)."))
	tbl = getEnrichmentTables(job, ontology = all_ontologies, verbose = FALSE)

	ui = fluidPage(
		h2("Report for online GREAT analysis"),
		h3("Job description"),
		verbatimTextOutput(outputId = "job_desc"),
		HTML(qq("<h3>Global region-gene associations <a class='fake_link' data-toggle='tooltip' data-html='true' title='The plot can be made by <br><code>plotRegionGeneAssociationGraphs(job)</code>.' onclick='false'>?</a></h3>")),
		HTML("<script>$('h3 a').tooltip();</script>"),
		plotOutput(outputId = "global_plot", width = "1000px", height= "400px"),
		hr(),
		h3("Global controls"),
		div(id = "global_control",
			tags$table(tags$tr(
				tags$td(textInput("padj_cutoff", label = "Cutoff for adjusted p-values (from Binomial test)", value = "0.05", width = 380)),
				tags$td(textInput("observed_hits_cutoff", label = "Cutoff for observed region hits", value = "0", width=400))
			))
		),
		hr(),
		htmlOutput(outputId = "error"),
		htmlOutput(outputId = "enrichment_table"),
		hr(),
		HTML("<p>Generated by <a href='https://bioconductor.org/packages/rGREAT/' target='_blank'>rGREAT package</a>.</p>"),
		tags$style(
"pre {
	width:800px;
	padding:20px;
}
#global_control td {padding-right:20px;}
.tooltip-inner {
	max-width:600px;
	background-color: #f5f5f5;
	border: 1px solid #cccccc;
	color: black;
	font-size:13px;
	padding: 6px 15px;
}
.fake_link {
    color: #337ab7;
    text-decoration: none;
}
.fake_link:hover {
	ext-decoration: underline;
	cursor: pointer;
}
.container-fluid {
	margin-left:20px;
	margin-right:20px
}
#error {
	color:red;
}
"
		)
	)

	format_table = function(tb, onto) {
		tb2 = tb[, c("ID", "name", "Binom_Raw_PValue", "Binom_Adjp_BH", "Binom_Fold_Enrichment", "Binom_Observed_Region_Hits", "Binom_Genome_Fraction",
			 "Hyper_Raw_PValue", "Hyper_Adjp_BH", "Hyper_Observed_Gene_Hits", "Hyper_Total_Genes")]
		
		BASE_URL = BASE_URL_LIST[job@parameters$version]

		tb2[, "name"] = qq("<a href='@{BASE_URL}/showTermDetails.php?termId=@{tb2[, 'ID']}&ontoName=@{job@job_env$ONTOLOGY_KEYS[onto]}&ontoUiName=@{onto}&sessionName=@{job@job_env$id}&species=@{job@parameters$species}&foreName=@{basename(param(job, 'f_bed'))}&backName=@{basename(param(job, 'f_bed_bg'))}&table=region' target='_blank'>@{tb2[, 'name']}</a>", collapse = FALSE)
		colnames(tb2) = c("ID", "Term Name", "Binom Raw P-value", "Binom Adjusted P-value", "Binom Fold Enrichment", "Binom Observed Region Hits", "Genome Fraction",
			"Hyper Raw P-value", "Hyper Adjusted P-value", "Hyper Observed Gene Hits", "Hyper Total Genes in Gene Set")
		colnames(tb2) = gsub("_", " ", colnames(tb2))

		dt = datatable(tb2[, -1], escape = FALSE, rownames = FALSE, selection = 'none', width = "100%", height = "auto",
			options = list(searching = FALSE, rowCallback = JS(
	'function(row, data) {
		$(this.api().cell(row, 1).node()).html(data[1].toExponential(3));
		$(this.api().cell(row, 2).node()).html(data[2].toExponential(3));
		$(this.api().cell(row, 6).node()).html(data[5].toExponential(3));
		$(this.api().cell(row, 7).node()).html(data[6].toExponential(3));
	}
	')))
		dt = formatRound(dt, "Binom Fold Enrichment", 3)
		dt = formatPercentage(dt, "Genome Fraction", 3)

		dt
	}

	server = function(input, output, session) {
		output$job_desc = renderPrint({
			show(job)

			cat("Cutoff for adjusted p-values (from Binomial test): ", input$padj_cutoff, "\n", sep = "")
			cat("Cutoff for observed region hits: ", input$observed_hits_cutoff, "\n", sep = "")
		})

		observe({

			suppressWarnings(padj_cutoff <- as.numeric(input$padj_cutoff))
			suppressWarnings(observed_hits_cutoff <- as.numeric(input$observed_hits_cutoff))

			if(is.na(padj_cutoff) || is.na(observed_hits_cutoff)) {
				output[["error"]] = renderUI({
					HTML("<p class='error'>Wrong format for cutoffs.</p>")
				})

				output[["enrichment_table"]] = renderUI({
					HTML("")
				})
				return(NULL)
			}

			all_ontologies = availableOntologies(job)
			tbl = getEnrichmentTables(job, ontology = all_ontologies, verbose = FALSE)
			tbl = lapply(tbl, function(tb) {
				tb[tb[, "Binom_Adjp_BH"] <= padj_cutoff & tb[, "Binom_Observed_Region_Hits"] >= observed_hits_cutoff, , drop = FALSE]
			})

			tbl = tbl[sapply(tbl, nrow) > 0]

			if(length(tbl) == 0) {
				output[["error"]] = renderUI({
					HTML("");
				})

				output[["enrichment_table"]] = renderUI({
					HTML("<p>No significant term under current cutoffs.</p>")
				})
			} else {
				ui_list = list()
				for(i in seq_along(tbl)) {
					ui_list[[2*i-1]] = HTML(qq("<h3>@{names(tbl)[i]} (@{nrow(tbl[[i]])} significant terms) <a class='fake_link' data-toggle='tooltip' data-html='true' title='The complete table can be obtained by <br><code>getEnrichmentTables(job, ontology = \"@{names(tbl)[i]}\")[[1]]</code>.' onclick='false'>?</a></h3>"))

					ui_list[[2*i]] = format_table(tbl[[i]], names(tbl)[i])
				}
				ui_list[[2*i + 1]] = HTML("<script>$('#enrichment_table h3 a').tooltip();</script>")

				ui_list$class = "ind_table"

				output[["error"]] = renderUI({
					HTML("");
				})
				output[["enrichment_table"]] = renderUI({
					do.call("div", ui_list)
				})
			}
		})

		output$global_plot = renderPlot({
			plotRegionGeneAssociations(job)
		}, res = 100)

	}

	shinyApp(ui, server)
})


# == title
# Shiny app on the GreatObject object
#
# == param
# -object The ``GreatObject`` object returned by `great`.
#
# == value
# A shiny app object.
#
# == example
# if(FALSE) {
# # pseudo code
# obj = great(...)
# shinyReport(obj)
# }
setMethod(f = "shinyReport",
	signature = "GreatObject",
	definition = function(object) {

	object = object

	ui = fluidPage(
		h2("Report for local GREAT analysis"),
		h3("Job description"),
		verbatimTextOutput(outputId = "job_desc"),
		HTML(qq("<h3>Global region-gene associations <a class='fake_link' data-toggle='tooltip' data-html='true' title='The plot can be made by <br><code>plotRegionGeneAssociationGraphs(object)</code>.' onclick='false'>?</a></h3>")),
		HTML("<script>$('h3 a').tooltip();</script>"),
		plotOutput(outputId = "global_plot", width = "1000px", height= "400px"),
		hr(),
		h3("Global controls"),
		div(id = "global_control",
			tags$table(tags$tr(
				tags$td(textInput("padj_cutoff", label = "Cutoff for adjusted p-values (from Binomial test)", value = "0.05", width = 380)),
				tags$td(textInput("observed_hits_cutoff", label = "Cutoff for observed region hits", value = "0", width=400))
			))
		),
		hr(),
		htmlOutput(outputId = "error"),
		htmlOutput(outputId = "enrichment_table"),
		tags$style(
"pre {
	width:800px;
	padding:20px;
}
#global_control td {
	padding-right:20px;
}
.tooltip-inner {
	max-width:400px;
	background-color: #f5f5f5;
	border: 1px solid #cccccc;
	color: black;
	font-size:13px;
	padding: 6px 15px;
}
.fake_link {
    color: #337ab7;
    text-decoration: none;
}
.fake_link:hover {
	ext-decoration: underline;
	cursor: pointer;
}
.container-fluid {
	margin-left:20px;
	margin-right:20px
}
#error {
	color:red;
}
.modal-lg {
	width:1100px;
}
"
		),
		hr(),
		HTML("<p>Generated by <a href='https://bioconductor.org/packages/rGREAT/' target='_blank'>rGREAT package</a>.</p>")
	)

	format_table = function(tb) {
		tb$id = qq("<a class='fake_link' onclick=\"Shiny.onInputChange('select_term', '');Shiny.onInputChange('select_term', '@{tb$id}');false;\">@{tb$id}</a>", collapse = FALSE)
			
		if("description" %in% colnames(tb)) {
			offset = 1
			tb = tb[, c("id", "description", "p_value", "p_adjust", "fold_enrichment", "observed_region_hits", "genome_fraction", "observed_gene_hits", "gene_set_size")]
			colnames(tb) = c("Term Name", "Term Description", "Binom Raw P-value", "Binom Adjusted P-value", "Binom Fold Enrichment", "Binom Observed Region Hits", "Genome Fraction", "Observed Gene Hits", "Total Genes in Gene Set")
		} else {
			offset = 0
			tb = tb[, c("id", "p_value", "p_adjust", "fold_enrichment", "observed_region_hits", "genome_fraction", "observed_gene_hits", "gene_set_size")]
			colnames(tb) = c("Term Name", "Binom Raw P-value", "Binom Adjusted P-value", "Binom Fold Enrichment", "Binom Observed Region Hits", "Genome Fraction", "Observed Gene Hits", "Total Genes in Gene Set")
		}

		dt = datatable(tb, escape = FALSE, rownames = FALSE, selection = 'none', width = "100%", height = "auto",
			options = list(searching = FALSE, rowCallback = JS(qq(
	'function(row, data) {
		$(this.api().cell(row, @{1+offset}).node()).html(data[@{1+offset}].toExponential(3));
		$(this.api().cell(row, @{2+offset}).node()).html(data[@{2+offset}].toExponential(3));
	}
	'))))
		dt = formatRound(dt, "Binom Fold Enrichment", 3)
		dt = formatPercentage(dt, "Genome Fraction", 3)

		dt
	}

	server = function(input, output, session) {
		output$job_desc = renderPrint({
			show(object)

			cat("\n")
			cat("Cutoff for adjusted p-values (from Binomial test): ", input$padj_cutoff, "\n", sep = "")
			cat("Cutoff for observed region hits: ", input$observed_hits_cutoff, "\n", sep = "")
		})
		
		observe({

			suppressWarnings(padj_cutoff <- as.numeric(input$padj_cutoff))
			suppressWarnings(observed_hits_cutoff <- as.numeric(input$observed_hits_cutoff))

			if(is.na(padj_cutoff) || is.na(observed_hits_cutoff)) {
				output[["error"]] = renderUI({
					HTML("<p class='error'>Wrong format for cutoffs.</p>")
				})

				output[["enrichment_table"]] = renderUI({
					HTML("")
				})
				return(NULL)
			}

			tb = getEnrichmentTable(object, min_region_hits = observed_hits_cutoff)
			tb = tb[tb$p_adjust <= padj_cutoff, , drop = FALSE]

			if(nrow(tb) == 0) {
				output[["error"]] = renderUI({
					HTML("");
				})
				output[["enrichment_table"]] = renderUI({
					HTML("<p>No significant term under current cutoffs.</p>")
				})
			} else {
				output[["error"]] = renderUI({
					HTML("");
				})
				output[["enrichment_table"]] = renderUI({
					div(
						HTML(qq("<h3>Enrichment table (@{nrow(tb)} significant terms) <a class='fake_link' data-toggle='tooltip' data-html='true' title='The complete table can be obtained by <code>getEnrichmentTable(object)</code>.' onclick='false'>?</a></h3>")),
						HTML("<script>$('#enrichment_table h3 a').tooltip();</script>"),
						format_table(tb)
					)
				})
			}
		})

		observeEvent(input$select_term, {
			term = input$select_term

			tb = getRegionGeneAssociations(object, term_id = term)
			tb = as.data.frame(tb)
			colnames(tb) = c("Chromosome", "Start", "End", "Width", "Strand", "Annotated Genes", "Distance to Genes")
			tb = tb[, -5]

			showModal(modalDialog(
		        title = qq("Region-gene associations for term: @{term}"),
		        plotOutput(outputId = "select_term_plot", width = "1000px", height= "400px"),
		        hr(),
		        renderDT(datatable(tb, escape = FALSE, rownames = FALSE, selection = 'none', 
					options = list(searching = FALSE))),
		        easyClose = TRUE,
		        size = "l"
		    ))
		})

		output$select_term_plot = renderPlot({
			term = input$select_term
			plotRegionGeneAssociations(object, term_id = term)
		})

		output$global_plot = renderPlot({
			plotRegionGeneAssociations(object)
		}, res = 100)
	}

	shinyApp(ui, server)
})

